# Site settings
title: 로보에널리스트 alphaV 랜딩페이지
description: 가치투자를 위한 기업분석을 자동으로 해주는 로보에널리스트 alphaV의 렌딩페이지
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://alpha-v-app.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: alphaV
user_description: 가치투자를 위한 기업분석을 자동으로 해주는 로보에널리스트
user_title: 당신의 가치투자를 위해 기업을 분석해주는 로보에널리스트
email: tobig.guys@gmail.com
twitter_username: 2biguys
github_username:  2biguys
gplus_username:  2biguys
disqus_username: 2biguys

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Download
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
